# Generated by Django 5.2.7 on 2026-05-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecord',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
